version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  emergency-notification-service:
    build:
      context: ./emergency-notification-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - ./emergency-notification-service/.env

  non-emergency-notification-service:
    build:
      context: ./non-emergency-notification-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - ./non-emergency-notification-service/.env

  notification-service:
    build:
      context: ./notification-sending-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - ./notification-sending-service/.env

  user-booking-service:
    build:
      context: ./user-booking-service
      dockerfile: Dockerfile
    env_file:
      - ./user-booking-service/.env
    depends_on:
      - mongo

  flight-data-service:
    build:
      context: ./flight-data-service
      dockerfile: Dockerfile
    ports:
      - '3002:3000'
    env_file:
      - ./flight-data-service/.env
    volumes:
      - ./flight-data-service:/app

  mongo:
    image: 'mongo:latest'
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  rabbitmq_data:
  mongo_data:
