version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  emergency-notification-service:
    build:
      context: ./emergency-notification-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq

  non-emergency-notification-service:
    build:
      context: ./non-emergency-notification-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq

  notification-service:
    build:
      context: ./notification-sending-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - EMAIL_USER=your-email@example.com
      - EMAIL_PASS=your-email-password

  user-booking-service:
    build:
      context: ./user-booking-service
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: 'mongo:latest'
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  rabbitmq_data:
  mongo_data:
